#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Run as root."
    exit 1
fi

LAB_ROOT="/opt/incident-lab"

STATE_FILE="$LAB_ROOT/incident-state/current-incident"
INCIDENT_DIR="$LAB_ROOT/incidents"

if [ -f "$STATE_FILE" ]; then
    echo "ERROR: Active incident detected."
    echo
    echo "Run incident-reset before starting a new incident."
    exit 1
fi

INCIDENT_NAME=$(
    find "$INCIDENT_DIR" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d |
    shuf -n 1 |
    xargs basename
)

SCRIPT_FILE="$INCIDENT_DIR/${INCIDENT_NAME}/incident.sh"
META_FILE="$INCIDENT_DIR/${INCIDENT_NAME}/incident.meta"

if [ ! -f "$SCRIPT_FILE" ]; then
    echo "ERROR: Incident script not found."
    exit 1
fi

if [ ! -f "$META_FILE" ]; then
    echo "ERROR: Incident metadata not found."
    exit 1
fi

if ! bash "$SCRIPT_FILE"; then
    echo "ERROR: Incident injection failed."
    exit 1
fi

if ! source "$META_FILE"; then
    echo "ERROR: Metadata loading failed."
    exit 1
fi

echo "$INCIDENT_NAME" > "$STATE_FILE"

echo "Incident created."
echo
echo "TICKET: $TICKET"
